### PR TITLE
Bump to a customised version of resemble for node 8+.

### PR DESCRIPTION
**Pull request by alexjeffburke**

### CODE REVIEW

**Comment by alexjeffburke** [comment]
This PR restores the ability to install the plugin on (at least) node 8.

**Comment by papandreou** [comment]
Just as a sanity check I wanted to see the current version fail first, so I went `rm -fr node_modules && npm install && npm test` on the current master with node 8.9.3 -- and it worked:

```
> unexpected-resemble@3.1.0 test /home/andreas/work/unexpected-resemble
> mocha ./documentation/**/*.md ./test/**/*.js && npm run lint



  to-resemble
    ✓ example #1 (documentation/assertions/any/to-resemble.md:4:1) should fail with the correct error message (205ms)

  index
    ✓ example #1 (documentation/index.md:23:1) should fail with the correct error message (38ms)
    ✓ example #2 (documentation/index.md:45:1) should succeed (45ms)

  unexpected-resemble
    ✓ should succeed when the comparison is successful (58ms)
    ✓ should fail when the comparison is unsuccessful (137ms)
    ✓ should compare images provided as data: urls
    with mismatchPercentage in odd camel case
      ✓ should succeed when the comparison is successful (59ms)
      ✓ should fail when the comparison is unsuccessful (174ms)


  8 passing (746ms)
```

Could we take it from the top? What exactly did you see when it failed initially?

**Comment by alexjeffburke** [comment]
Hmm we’re you on linux by chance? I’m pretty sure the issues start when you’re compiling with clang... I could reliably get it to fail until canvas v1.6.3 which has a fix in it specifically for that situation on macOS. Trying to think what else might be relevant - I was using node 8.9.1 so I think it was a thing. I noticed the travis job forces the use of gcc and am wondering if that masked it in CI.

**Comment by papandreou** [comment]
Yeah, I'm on linux, I guess you're not?

**Comment by alexjeffburke** [comment]
That’ll be it, it’s the compiler - my understanding of the the as-is version of nan is it’s unhappy with clang.

**Comment by alexjeffburke** [comment]
And sorry, to make sure it’s captured - I was putting this together on macOS 10.12 :)

**Comment by papandreou** [comment]
Thanks, I've published 3.2.0 with this change. I bisected and found out that 7c5491692f was what broke the browser build, so I also reverted that.

Tried getting rid of the `resemble` module and also tried upgrading `resemblejs` to the newest version. Both attempts caused the test suite to fail right and left, so...

Byebye

**Comment by alexjeffburke** [comment]
Haha after my brief encounter I second the above :P Thanks for looking into it & getting the change out!

**Pull request merged**
